jobs:
  main:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./verify/run

name: Verify

on:
  schedule:
    - cron: "50 2/3 * * *"
